name: fabfos
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - packaging>=21.3
  - bwa>=0.7.17
  - samtools>=1.15.1
  - trimmomatic>=0.39
  - blast
  - megahit
  - spades
  - pip
  - pip:
    - pyfastx==1.1
